import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.117.2";
type Job={shipment_id:string;order_id:string;tracking_number:string;carrier:string|null;current_tracking_status:string};
type ProviderConfig={carrier:string;enabled:boolean;adapter_type:"NORMALIZED_JSON";endpoint_url:string;http_method:"GET"|"POST";timeout_ms:number};
type NormalizedEvent={event_time:string;normalized_status?:string;status?:string;raw_status?:string|null;description?:string|null;raw_description?:string|null;location?:string|null;raw_location?:string|null;normalized_location?:string|null;destination_hub?:string|null};
type RequestMode="AUTO"|"MANUAL";
const ALLOWED_STATUSES=new Set(["READY_TO_SHIP","PICKED_UP","IN_TRANSIT","ARRIVED_TRANSIT_HUB","ARRIVED_DESTINATION_HUB","OUT_FOR_DELIVERY","DELIVERY_FAILED","DELIVERED","CANCELLED","RETURNING","RETURNED","UNKNOWN"]);
const supabaseUrl=Deno.env.get("SUPABASE_URL");const serviceRoleKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!supabaseUrl||!serviceRoleKey)throw new Error("Missing Supabase runtime variables");
const db=createClient(supabaseUrl,serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}});
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8"}})}
function bangkokHour(date=new Date()){return Number(new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Bangkok",hour:"2-digit",hourCycle:"h23"}).format(date))}
async function sha256(input:string){const bytes=new TextEncoder().encode(input);const digest=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,"0")).join("")}
function safeProviderUrl(raw:string){const url=new URL(raw);if(url.protocol!=="https:")throw new Error("Provider endpoint must use HTTPS");const host=url.hostname.toLowerCase();if(host==="localhost"||host==="127.0.0.1"||host==="::1"||host.endsWith(".local"))throw new Error("Local provider endpoints are not allowed");return url}
async function authorize(req:Request):Promise<RequestMode|null>{const supplied=req.headers.get("x-cron-secret")??"";if(supplied){const{data,error}=await db.rpc("verify_tracking_cron_secret",{p_secret:supplied});if(!error&&data===true)return"AUTO"}const auth=req.headers.get("authorization")??"";if(auth.toLowerCase().startsWith("bearer ")){const token=auth.slice(7).trim();const{data,error}=await db.auth.getUser(token);const role=data.user?.app_metadata?.role;if(!error&&data.user&&(role==="admin"||role==="operator"))return"MANUAL"}return null}
async function fetchProvider(config:ProviderConfig,job:Job):Promise<NormalizedEvent[]>{const url=safeProviderUrl(config.endpoint_url);const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),Math.min(Math.max(config.timeout_ms??8000,1000),30000));try{let response:Response;if(config.http_method==="POST"){response=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({tracking_number:job.tracking_number,carrier:job.carrier}),signal:controller.signal})}else{url.searchParams.set("tracking_number",job.tracking_number);if(job.carrier)url.searchParams.set("carrier",job.carrier);response=await fetch(url,{signal:controller.signal})}if(!response.ok)throw new Error(`Provider HTTP ${response.status}`);const payload=await response.json();const events=Array.isArray(payload)?payload:payload?.events;if(!Array.isArray(events))throw new Error("Provider payload must contain an events array");return events}finally{clearTimeout(timeout)}}
async function processJob(job:Job,syncSource:RequestMode){const startedAt=new Date().toISOString();const{data:logRow,error:logError}=await db.from("tracking_sync_logs").insert({shipment_id:job.shipment_id,source:syncSource,started_at:startedAt}).select("id").single();if(logError)throw logError;try{if(!job.carrier)throw new Error("Shipment carrier is missing");const{data:config,error:configError}=await db.from("tracking_provider_configs").select("carrier,enabled,adapter_type,endpoint_url,http_method,timeout_ms").ilike("carrier",job.carrier).eq("enabled",true).maybeSingle();if(configError)throw configError;if(!config)throw new Error(`Provider adapter is not configured for ${job.carrier}`);const events=(await fetchProvider(config as ProviderConfig,job)).slice().sort((a,b)=>new Date(a.event_time).getTime()-new Date(b.event_time).getTime());if(events.length===0){const{error}=await db.rpc("complete_tracking_no_change",{p_shipment_id:job.shipment_id});if(error)throw error}else{for(const event of events){const status=String(event.normalized_status??event.status??"UNKNOWN").toUpperCase();if(!ALLOWED_STATUSES.has(status))throw new Error(`Unsupported normalized status: ${status}`);if(!event.event_time||Number.isNaN(new Date(event.event_time).getTime()))throw new Error("Invalid event_time");const rawStatus=event.raw_status??event.status??status;const rawLocation=event.raw_location??event.location??null;const fingerprint=await sha256([job.tracking_number,event.event_time,rawStatus??"",rawLocation??"",status].join("|"));const{error}=await db.rpc("apply_tracking_event",{p_shipment_id:job.shipment_id,p_event_time:event.event_time,p_raw_status:rawStatus,p_raw_description:event.raw_description??event.description??null,p_raw_location:rawLocation,p_normalized_status:status,p_normalized_location:event.normalized_location??event.location??null,p_destination_hub:event.destination_hub??null,p_source:"CARRIER",p_fingerprint:fingerprint});if(error)throw error}}await db.from("tracking_sync_logs").update({completed_at:new Date().toISOString(),result:"SUCCESS",new_event_count:events.length}).eq("id",logRow.id);return{shipment_id:job.shipment_id,ok:true,event_count:events.length}}catch(error){const message=error instanceof Error?error.message:String(error);await db.rpc("mark_tracking_failure",{p_shipment_id:job.shipment_id,p_error_code:"TRACKING_PROVIDER_ERROR",p_error_message:message});await db.from("tracking_sync_logs").update({completed_at:new Date().toISOString(),result:"FAILED",error_code:"TRACKING_PROVIDER_ERROR",error_message:message.slice(0,1000)}).eq("id",logRow.id);return{shipment_id:job.shipment_id,ok:false,error:message}}}
Deno.serve(async(req)=>{if(req.method!=="POST")return json({error:"Method not allowed"},405);const mode=await authorize(req);if(!mode)return json({error:"Unauthorized"},401);let body:{limit?:number;shipment_id?:string}={};try{body=await req.json()}catch{}if(mode==="MANUAL"){if(!body.shipment_id)return json({error:"shipment_id is required for manual sync"},400);const{data:jobs,error}=await db.rpc("claim_manual_shipment",{p_shipment_id:body.shipment_id});if(error)return json({error:error.message},409);if(!jobs?.length)return json({error:"Shipment is not available for manual sync"},409);const result=await processJob((jobs as Job[])[0],"MANUAL");return json({ok:result.ok,manual:true,result},result.ok?200:502)}const hour=bangkokHour();if(hour>=2&&hour<6)return json({ok:true,quiet_hours:true,claimed:0,results:[]});const limit=Math.min(Math.max(Number(body.limit??30),1),50);const{data:jobs,error:claimError}=await db.rpc("claim_due_shipments",{p_limit:limit});if(claimError)return json({error:claimError.message},500);if(!jobs?.length)return json({ok:true,quiet_hours:false,claimed:0,results:[]});const results:unknown[]=[];const concurrency=5;for(let i=0;i<jobs.length;i+=concurrency){const chunk=(jobs as Job[]).slice(i,i+concurrency);results.push(...await Promise.all(chunk.map(job=>processJob(job,"AUTO"))))}return json({ok:true,quiet_hours:false,claimed:jobs.length,results})});