import Link from 'next/link'
import { requireUser } from '@/lib/supabase/auth'
import { formatDateTime, formatMoney, formatPhone, sourceLabel, statusLabel } from '@/lib/format'
import { ManualSyncButton } from '@/components/manual-sync-button'
import { createOrder, replaceShipment } from '@/lib/actions/core'
import { CopyOrderButton } from '@/components/copy-order-button'

type SP={order?:string,receive?:string,mode?:string,tab?:string}
export default async function OrdersPage({searchParams}:{searchParams:Promise<SP>}){
  const sp=await searchParams; const {supabase,user}=await requireUser(); const role=String(user.app_metadata?.role??'viewer')
  let q=supabase.from('orders').select('id,shopee_order_id,erp_user_id,recipient_name,recipient_phone,recipient_address,destination_hub,cod,receive_status,warehouse_status,created_at,erp_users(username),shipments(id,tracking_number,carrier,current_tracking_status,is_active,tracking_enabled,next_track_at)').order('created_at',{ascending:false}).limit(100)
  if(sp.receive)q=q.eq('receive_status',sp.receive)
  const [{data,error},{data:userOptions}]=await Promise.all([q,supabase.from('erp_users').select('id,username').order('username').limit(500)]); const rows=(data??[]) as any[]
  let detail:any=null, items:any[]=[], trackingEvents:any[]=[], auditRows:any[]=[]
  if(sp.order){
    const [od,it]=await Promise.all([
      supabase.from('orders').select('id,shopee_order_id,recipient_name,recipient_phone,recipient_address,destination_hub,cod,receive_status,warehouse_status,created_at,erp_users(username),shipments(id,tracking_number,carrier,current_tracking_status,is_active,tracking_enabled,last_track_at,next_track_at)').eq('id',sp.order).maybeSingle(),
      supabase.from('order_items').select('*').eq('order_id',sp.order),
    ]); detail=od.data; items=(it.data??[]) as any[]
    const shipmentIds=(detail?.shipments??[]).map((x:any)=>x.id)
    if((sp.tab==='tracking'||!sp.tab)&&shipmentIds.length){const ev=await supabase.from('tracking_events').select('*').in('shipment_id',shipmentIds).order('event_time',{ascending:false}).limit(100);trackingEvents=(ev.data??[]) as any[]}
    if(sp.tab==='history'){const au=await supabase.from('audit_logs').select('*').eq('entity_id',sp.order).order('created_at',{ascending:false}).limit(100);auditRows=(au.data??[]) as any[]}
  }
  return <><header className="page-head"><div><h1>Quản lý đơn hàng</h1><p>Dữ liệu đơn hàng, vận đơn và hành trình được quản lý tách biệt</p></div><div className="head-actions"><button className="button" disabled>Lọc theo ngày</button><Link className="button primary" href="/orders?mode=create">+ Tạo đơn</Link></div></header>
  <div className={`split-view ${(detail||sp.mode==='create')?'with-panel':''}`}><section><div className="toolbar"><input className="search" placeholder="Tìm mã đơn / mã vận đơn / tài khoản" disabled/><div className="segmented"><Link className={!sp.receive?'active':''} href="/orders">Tất cả</Link><Link className={sp.receive==='WAITING_RECEIVE'?'active':''} href="/orders?receive=WAITING_RECEIVE">Chờ nhận</Link><Link className={sp.receive==='RECEIVED'?'active':''} href="/orders?receive=RECEIVED">Đã nhận</Link></div><span className="toolbar-note">{rows.length} đơn</span></div><div className="card table-card"><table className="table"><thead><tr><th>#</th><th>Mã đơn</th><th>Tài khoản</th><th>Mã vận đơn</th><th>Đơn vị vận chuyển</th><th>Tiền thu hộ</th><th>Vận chuyển</th><th>Nhận hàng</th><th>Kho đích</th></tr></thead><tbody>{error?<tr><td colSpan={9} className="error-text">{error.message}</td></tr>:!rows.length?<tr><td colSpan={9} className="empty">Chưa có đơn hàng trong hệ thống.</td></tr>:rows.map((o,i)=>{const s=(o.shipments??[]).find((x:any)=>x.is_active)??o.shipments?.[0];return <tr key={o.id} className={sp.order===o.id?'selected-row':''}><td>{i+1}</td><td><Link className="table-link" href={`/orders?${sp.receive?`receive=${sp.receive}&`:''}order=${o.id}`}>{o.shopee_order_id??o.id.slice(0,8)}</Link></td><td>{o.erp_users?.username??'—'}</td><td>{s?.tracking_number??'Chưa có'}</td><td>{s?.carrier??'—'}</td><td className="money">{formatMoney(o.cod)}</td><td><span className={`status-pill status-${String(s?.current_tracking_status??'UNKNOWN').toLowerCase()}`}>{statusLabel(s?.current_tracking_status)}</span></td><td><span className={`status-pill ${o.receive_status==='RECEIVED'?'green':o.receive_status==='WAITING_RECEIVE'?'orange':''}`}>{statusLabel(o.receive_status)}</span></td><td>{o.destination_hub??'—'}</td></tr>})}</tbody></table></div></section>
  {sp.mode==='create'&&<aside className="detail-panel"><div className="panel-head"><div><span className="eyebrow">ĐƠN HÀNG</span><h2>Tạo đơn mới</h2></div><Link className="close" href="/orders">×</Link></div><form action={createOrder} className="panel-form panel-scroll"><div className="form-grid"><label>Mã đơn Shopee<input name="shopee_order_id"/></label><label>Tài khoản<select name="erp_user_id" defaultValue=""><option value="">— Chọn tài khoản —</option>{(userOptions??[]).map(u=><option key={u.id} value={u.id}>{u.username}</option>)}</select></label></div><div className="form-grid"><label>Mã vận đơn<input name="tracking_number"/></label><label>Đơn vị vận chuyển<input name="carrier" placeholder="Ví dụ: SPX Express"/></label></div><label>Tiền thu hộ<input name="cod" inputMode="numeric" defaultValue="0"/></label><div className="form-grid"><label>Người nhận<input name="recipient_name"/></label><label>Số điện thoại người nhận<input name="recipient_phone"/></label></div><label>Địa chỉ<input name="recipient_address"/></label><label>Kho đích<input name="destination_hub"/></label><div className="form-actions"><Link className="button" href="/orders">Hủy</Link><button className="button primary">Tạo đơn</button></div></form></aside>}{detail&&<aside className="detail-panel"><div className="panel-head"><div><span className="eyebrow">CHI TIẾT ĐƠN</span><h2>{detail.shopee_order_id??detail.id.slice(0,8)}</h2></div><Link className="close" href={sp.receive?`/orders?receive=${sp.receive}`:'/orders'}>×</Link></div><div className="panel-tabs"><Link className={!sp.tab||sp.tab==='info'?'active':''} href={`/orders?order=${detail.id}&tab=info`}>Thông tin</Link><Link className={sp.tab==='tracking'?'active':''} href={`/orders?order=${detail.id}&tab=tracking`}>Vận chuyển</Link><Link className={sp.tab==='history'?'active':''} href={`/orders?order=${detail.id}&tab=history`}>Lịch sử</Link></div><div className="panel-scroll">
{(!sp.tab||sp.tab==='info')&&<><div className="detail-grid"><div><span>Tài khoản</span><b>{detail.erp_users?.username??'—'}</b></div><div><span>Tiền thu hộ</span><b>{formatMoney(detail.cod)}</b></div><div><span>Người nhận</span><b>{detail.recipient_name??'—'}</b></div><div><span>Số điện thoại</span><b>{formatPhone(detail.recipient_phone)}</b></div><div className="full"><span>Địa chỉ</span><b>{detail.recipient_address??'—'}</b></div><div><span>Kho đích</span><b>{detail.destination_hub??'—'}</b></div><div><span>Nhận hàng</span><b>{statusLabel(detail.receive_status)}</b></div></div><div className="panel-action-row"><CopyOrderButton text={`Mã đơn: ${detail.shopee_order_id??''}\nCOD: ${detail.cod??0}\nNgười nhận: ${detail.recipient_name??''}\nSĐT: ${detail.recipient_phone??''}\nĐịa chỉ: ${detail.recipient_address??''}`}/></div><h3>Sản phẩm</h3><div className="mini-table"><div className="mini-head"><span>Sản phẩm</span><span>Mã SKU / Phân loại</span><span>Số lượng</span><span>Giá</span></div>{!items.length?<div className="empty compact">Chưa có sản phẩm.</div>:items.map((it:any)=><div className="mini-row" key={it.id}><span>{it.product_name??it.name??'Sản phẩm'}</span><span>{[it.sku,it.variant??it.classification].filter(Boolean).join(' · ')||'—'}</span><span>{it.quantity??1}</span><span>{formatMoney(it.final_price??it.original_price??it.price)}</span></div>)}</div></>}
{sp.tab==='tracking'&&<><h3>Vận đơn đang sử dụng</h3>{!(detail.shipments??[]).length?<div className="empty compact">Chưa có mã vận đơn.</div>:(detail.shipments??[]).map((s:any)=><div className={`shipment-box ${s.is_active?'active-shipment':''}`} key={s.id}><div className="shipment-top"><div><span className="muted">{s.carrier??'Đơn vị vận chuyển'} {s.is_active?'· ĐANG DÙNG':'· ĐÃ THAY'}</span><b>{s.tracking_number}</b></div><span className={`status-pill status-${String(s.current_tracking_status).toLowerCase()}`}>{statusLabel(s.current_tracking_status)}</span></div><div className="meta-row"><span>Lần đồng bộ cuối: {formatDateTime(s.last_track_at)}</span><span>Lần kế tiếp: {formatDateTime(s.next_track_at)}</span></div>{s.is_active&&<ManualSyncButton shipmentId={s.id}/>}</div>)}{['admin','operator'].includes(role)&&<form action={replaceShipment} className="replace-form"><input type="hidden" name="order_id" value={detail.id}/><b>Cập nhật mã vận đơn</b><div className="form-grid"><input name="tracking_number" required placeholder="Mã vận đơn mới"/><input name="carrier" placeholder="Đơn vị vận chuyển"/></div><button className="button small primary">Lưu mã vận đơn mới</button></form>}<h3>Hành trình vận chuyển</h3><div className="timeline">{!trackingEvents.length?<div className="empty compact">Chưa có sự kiện vận chuyển.</div>:trackingEvents.map((e:any)=><div className="timeline-item" key={e.id}><i></i><div><b>{statusLabel(e.normalized_status)}</b><span>{e.raw_description??e.raw_status??'—'}</span><small>{formatDateTime(e.event_time)}{e.raw_location?` · ${e.raw_location}`:''}</small></div></div>)}</div></>}
{sp.tab==='history'&&<><h3>Lịch sử hệ thống</h3><div className="timeline">{!auditRows.length?<div className="empty compact">Chưa có lịch sử hệ thống cho đơn này.</div>:auditRows.map((a:any)=><div className="timeline-item" key={a.id}><i></i><div><b>{a.action??'CẬP NHẬT'}</b><span>{sourceLabel(a.source??a.module??'SYSTEM')}</span><small>{formatDateTime(a.created_at??a.time)}</small></div></div>)}</div></>}
<div className="panel-meta">Tạo đơn: {formatDateTime(detail.created_at)}</div></div></aside>}</div></>
}
