-- RETIRED: legacy finance demo seed (migration 0035).
-- This migration previously inserted sample customers, sales, payment receipts,
-- finance documents and ledger records. Fresh environments MUST start without
-- business demo data. Do not restore those INSERT statements to migrations.
--
-- The original sample SQL remains available in Git history at blob f6d59f940ec8a26d8aa4eaebf02f58960a634126.
-- The Supabase project's migration history is preserved; already-applied migrations
-- and existing records are NOT modified by retiring this repository file.
-- Any future test fixtures belong in explicitly isolated QA setup/cleanup scripts.
--
-- Intentionally no-op.
